/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Frontend;
import Backend.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author AbdElrahman
 */
public class Friends extends javax.swing.JDialog {
ArrayList<User> users=new ArrayList<>();
public ArrayList<User> loadElements(){
           ArrayList<String> friends = new ArrayList<>();
        friends.add("friend1");
        friends.add("friend2");

        ArrayList<String> blocked = new ArrayList<>();
        blocked.add("blockedUser1");

        Map<String, String> friendRequests = new HashMap<>();
        friendRequests.put("user3", "Pending");
        friendRequests.put("user4", "Accepted");

      

        // Setting friends, blocked users, and friend requests separately
        
     for (int i = 0; i < 5; i++) {
 UserBuilder userBuilder = new UserBuilder();
        User user = userBuilder
            .setId("id"+i)
            .setName("User"+i)
            .setEmail("johndoe@example.com")
            //.setSalt()   
            //.setPasswordManager(PasswordManager.getInstance())
            //.setPassword("password123")
            .setDateOfBirth("1990-01-01")
            .setUserPhoto("photoUrl.jpg")
            .setUserCover("coverUrl.jpg")
            .setUserBio("Hello! I'm John Doe.")
            .setStatus()
            
            .build();
userBuilder.setFriends(friends);
        userBuilder.setBlocked(blocked);
        
                    
         users.add(user);
        }
     users.get(1).getFriendReq().put("User3", "Pending");
     users.get(1).getFriendReq().put("User4", "Pending");
return users;
}
        
    /**
     * Creates new form FriendManagement
     */
    public Friends(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadList(loadElements());
    }
    public void loadList(ArrayList<User> users){
         ArrayList<String> names = new ArrayList<>();
    
    // Assuming you want to find friend requests for the first user in the list (index 0)
    User targetUser = users.get(1); // Specify the user you're interested in
    
    // Get the friend requests map for the target user
    Map<String, String> friendReq = targetUser.getFriendReq();
    
    // Iterate over the map to check for "Pending" requests
    for (Map.Entry<String, String> entry : friendReq.entrySet()) {
        if ("Pending".equals(entry.getValue())) {
            names.add(entry.getKey());  // Add the username (key) with the "Pending" status
        }
    }
    
    // Set the list data for your JList
    jList1.setListData(names.toArray(new String[0]));
        System.out.println(jList1.getSelectedValue()); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Add = new javax.swing.JButton();
        Decline = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Friend Requests");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Decline.setText("Decline");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Decline, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Add)
                        .addGap(41, 41, 41)
                        .addComponent(Decline))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
String s=jList1.getSelectedValue();
        System.out.println(s);
User targetUser = users.get(1);
FriendManagement f=new FriendManagement();
if(s==null)
 JOptionPane.showMessageDialog(this, "Must choose User","Error",JOptionPane.ERROR_MESSAGE);
else{
User r=users.get(3);
    try {
        f.acceptFriendRequest(targetUser,r);
    } catch (IOException ex) {
        Logger.getLogger(Friends.class.getName()).log(Level.SEVERE, null, ex);
    }
    JOptionPane.showMessageDialog(this, "Added succ","Error",JOptionPane.ERROR_MESSAGE);
 
}


        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Friends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Friends dialog = new Friends(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Decline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
